# Generated by Django 4.2.11 on 2024-10-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicoes', '0015_alter_servidor_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Equipamento')),
                ('numero_convenio', models.CharField(max_length=50, unique=True, verbose_name='Número do Convênio')),
            ],
        ),
        migrations.CreateModel(
            name='User_Agricultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoriazado', models.BooleanField(default=True)),
                ('servidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.servidor')),
            ],
        ),
    ]
