# Generated by Django 4.2.11 on 2024-10-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura_codigobarras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='codigo_barra',
            field=models.CharField(editable=False, max_length=22, null=True, unique=True),
        ),
    ]
