# Generated by Django 4.2.11 on 2024-10-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura_codigobarras', '0002_equipamento_codigo_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='codigo_barra',
            field=models.CharField(default='teste', editable=False, max_length=22, unique=True),
            preserve_default=False,
        ),
    ]
