# Generated by Django 4.2.16 on 2025-01-14 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ordem', models.IntegerField()),
                ('concluido', models.BooleanField(default=False)),
                ('data_execucao', models.DateField(blank=True, null=True, verbose_name='Data de execução')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='projetos/anexos/')),
                ('dt_inclusao', models.DateField(auto_now_add=True)),
                ('dt_att', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atividade da tarefa',
                'verbose_name_plural': 'Atividades das tarefas',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dt_inclusao', models.DateField(auto_now_add=True)),
                ('dt_att', models.DateField(auto_now=True)),
                ('user_inclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Categoria das tarefas',
                'verbose_name_plural': 'Categorias das tarefas',
            },
        ),
        migrations.CreateModel(
            name='Fases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('at', 'Ativo'), ('ar', 'Arquivado')], default='at', max_length=2)),
                ('ordem', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('dt_inclusao', models.DateField(auto_now_add=True)),
                ('dt_att', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fase do projeto',
                'verbose_name_plural': 'Fases dos projetos',
            },
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#FFFFFF', max_length=7)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Prioridade das tarefas',
                'verbose_name_plural': 'Prioridades das tarefas',
            },
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('orderm', models.IntegerField()),
                ('concluido', models.BooleanField(default=False)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='projetos/anexos/')),
                ('dt_inclusao', models.DateField(auto_now_add=True)),
                ('dt_att', models.DateField(auto_now=True)),
                ('categoria', models.ManyToManyField(to='projetos.categorias')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.fases')),
                ('prioridade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.prioridade')),
                ('user_inclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Tarefa do projeto',
                'verbose_name_plural': 'Tarefas dos projetos',
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('orcamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('P', 'Planejamento'), ('E', 'Execução'), ('F', 'Finalizado')], max_length=1)),
                ('dt_inclusao', models.DateField(auto_now_add=True)),
                ('dt_att', models.DateField(auto_now=True)),
                ('user_inclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Fase do projeto',
                'verbose_name_plural': 'Fases dos projetos',
            },
        ),
        migrations.AddField(
            model_name='fases',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projetos'),
        ),
        migrations.AddField(
            model_name='fases',
            name='user_inclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão'),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuicao', models.CharField(choices=[('t', 'Tarefa'), ('a', 'Atividade')], max_length=1)),
                ('descricao', models.TextField()),
                ('dt_inclusao', models.DateField(auto_now_add=True)),
                ('dt_att', models.DateField(auto_now=True)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.atividades')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.tarefas')),
                ('user_inclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Comentário da tarefa',
                'verbose_name_plural': 'Comentários das tarefas',
            },
        ),
        migrations.AddField(
            model_name='atividades',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.tarefas'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='user_inclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão'),
        ),
        migrations.AlterUniqueTogether(
            name='fases',
            unique_together={('projeto', 'ordem')},
        ),
    ]
