# Generated by Django 4.2.16 on 2025-01-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0016_alter_servidor_matricula'),
        ('projetos', '0002_remove_projetos_orcamento_alter_projetos_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fases',
            options={'verbose_name': 'Etapa do projeto', 'verbose_name_plural': 'Etapas dos projetos'},
        ),
        migrations.AddField(
            model_name='projetos',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='colaboradores', to='instituicoes.servidor'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.servidor'),
        ),
    ]
