# Generated by Django 4.2.16 on 2025-01-28 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0016_alter_servidor_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0003_alter_fases_options_projetos_colaboradores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='colaboradores',
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('dt_inclusao', models.DateField(auto_now_add=True)),
                ('dt_att', models.DateField(auto_now=True)),
                ('membros', models.ManyToManyField(blank=True, related_name='grupos', to='instituicoes.servidor')),
                ('user_inclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Grupo de servidores',
                'verbose_name_plural': 'Grupos de servidores',
            },
        ),
        migrations.AddField(
            model_name='projetos',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='grupos', to='projetos.grupo'),
        ),
    ]
