# Generated by Django 4.2.16 on 2025-01-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_remove_projetos_colaboradores_grupo_projetos_grupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='descricao',
        ),
    ]
