# Generated by Django 4.2.16 on 2025-01-29 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0016_alter_servidor_matricula'),
        ('projetos', '0005_remove_grupo_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.servidor'),
        ),
    ]
