# Generated by Django 4.2.16 on 2025-02-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0016_alter_servidor_matricula'),
        ('projetos', '0007_alter_fases_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='atribuicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atribuicao', to='instituicoes.servidor'),
        ),
    ]
