# Generated by Django 4.2.16 on 2025-02-18 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_tarefas_atribuicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='projetos/anexos/')),
                ('tipo', models.CharField(choices=[('t', 'Tarefa'), ('a', 'Atividade')], max_length=1)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos_atividade', to='projetos.atividades')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos_tarefa', to='projetos.tarefas')),
            ],
            options={
                'verbose_name': 'Anexo das tarefa ou das atividade',
                'verbose_name_plural': 'Anexos das tarefas e das atividades',
            },
        ),
    ]
