# Generated by Django 4.2.16 on 2025-02-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_comentarios_projeto_alter_comentarios_atribuicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
