# Generated by Django 4.2.11 on 2025-03-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_alter_comentarios_dt_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='status',
            field=models.CharField(choices=[('C', 'Planejamento'), ('E', 'Em andamento'), ('F', 'Finalizado'), ('P', 'Parado'), ('A', 'Arquivado')], default='C', max_length=1),
        ),
    ]
