# Generated by Django 4.2.16 on 2025-03-28 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0016_alter_servidor_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0012_alter_projetos_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('concluido', models.BooleanField(default=False)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('dt_inclusao', models.DateField(auto_now_add=True)),
                ('dt_att', models.DateField(auto_now=True)),
                ('referencia', models.CharField(choices=[('n', 'Nenhuma'), ('t', 'Tarefa'), ('a', 'Atividade')], default='n', max_length=1)),
                ('id_referencia', models.IntegerField(blank=True, null=True)),
                ('atribuicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas', to='instituicoes.servidor')),
                ('user_inclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
            },
        ),
    ]
