# Generated by Django 4.2.16 on 2025-03-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0014_demandas_prioridade_alter_demandas_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='data_prevista_execucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandas',
            name='dt_concluido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandas',
            name='rotina',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(2, 'Importante'), (1, 'Média'), (3, 'Urgente'), (0, 'Regular')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('a', 'Atividade'), ('t', 'Tarefa'), ('n', 'Nenhuma')], default='n', max_length=1),
        ),
    ]
