# Generated by Django 4.2.16 on 2025-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0016_alter_demandas_options_demandas_ordem_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(0, 'Regular'), (3, 'Urgente'), (2, 'Importante'), (1, 'Média')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('n', 'Nenhuma'), ('a', 'Gestão de Projetos'), ('t', 'Gestão de Projetos')], default='n', max_length=1),
        ),
    ]
