# Generated by Django 4.2.16 on 2025-04-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0017_alter_demandas_prioridade_alter_demandas_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Média'), (3, 'Urgente'), (2, 'Importante'), (0, 'Regular')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('a', 'Gestão de Projetos'), ('t', 'Gestão de Projetos'), ('n', 'Nenhuma')], default='n', max_length=1),
        ),
    ]
