# Generated by Django 4.2.16 on 2025-04-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0018_alter_demandas_prioridade_alter_demandas_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(2, 'Importante'), (0, 'Regular'), (1, 'Média'), (3, 'Urgente')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('p', 'Ação planejada'), ('a', 'Gestão de Projetos'), ('t', 'Gestão de Projetos'), ('n', 'Nenhuma')], default='n', max_length=1),
        ),
    ]
