# Generated by Django 4.2.16 on 2025-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0020_alter_demandas_prioridade_alter_demandas_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(0, 'Regular'), (2, 'Importante'), (3, 'Urgente'), (1, 'Média')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('a', 'Gestão de Projetos'), ('p', 'Ação planejada'), ('t', 'Gestão de Projetos'), ('n', 'Nenhuma')], default='n', max_length=1),
        ),
    ]
