# Generated by Django 4.2.16 on 2025-04-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0021_alter_demandas_prioridade_alter_demandas_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Média'), (3, 'Urgente'), (0, 'Regular'), (2, 'Importante')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('a', 'Gestão de Projetos'), ('n', 'Nenhuma'), ('p', 'Ação planejada'), ('t', 'Gestão de Projetos')], default='n', max_length=1),
        ),
    ]
