# Generated by Django 4.2.11 on 2025-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0022_alter_demandas_prioridade_alter_demandas_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(3, 'Urgente'), (1, 'Média'), (2, 'Importante'), (0, 'Regular')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('n', 'Nenhuma'), ('a', 'Gestão de Projetos'), ('p', 'Ação planejada'), ('t', 'Gestão de Projetos')], default='n', max_length=1),
        ),
    ]
