# Generated by Django 4.2.11 on 2025-05-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0024_alter_demandas_prioridade_alter_demandas_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Média'), (3, 'Urgente'), (2, 'Importante')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('p', 'Ação planejada'), ('t', 'Gestão de Projetos'), ('a', 'Gestão de Projetos'), ('n', 'Nenhuma')], default='n', max_length=1),
        ),
    ]
