# Generated by Django 4.2.16 on 2025-06-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0025_alter_demandas_prioridade_alter_demandas_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='status',
            field=models.CharField(choices=[('c', 'Concluído'), ('e', 'Em andamento'), ('x', 'Cancelado'), ('p', 'Em aberto')], default='p', max_length=1, verbose_name='Status da demanda'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(0, 'Regular'), (3, 'Urgente'), (1, 'Média'), (2, 'Importante')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('t', 'Gestão de Projetos'), ('p', 'Ação planejada'), ('a', 'Gestão de Projetos'), ('n', 'Nenhuma')], default='n', max_length=1),
        ),
    ]
