# Generated by Django 4.2.16 on 2025-06-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0026_demandas_status_alter_demandas_prioridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(0, 'Regular'), (2, 'Importante'), (3, 'Urgente'), (1, 'Média')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('t', 'Gestão de Projetos'), ('p', 'Ação planejada'), ('n', 'Nenhuma'), ('a', 'Gestão de Projetos')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='status',
            field=models.CharField(choices=[('e', 'Em andamento'), ('p', 'Em aberto'), ('c', 'Concluído'), ('x', 'Cancelado')], default='p', max_length=1, verbose_name='Status da demanda'),
        ),
    ]
