# Generated by Django 4.2.16 on 2025-06-04 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0016_alter_servidor_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0027_alter_demandas_prioridade_alter_demandas_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(3, 'Urgente'), (0, 'Regular'), (1, 'Média'), (2, 'Importante')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('a', 'Gestão de Projetos'), ('t', 'Gestão de Projetos'), ('n', 'Nenhuma'), ('p', 'Ação planejada')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='status',
            field=models.CharField(choices=[('c', 'Concluído'), ('p', 'Em aberto'), ('e', 'Em andamento'), ('x', 'Cancelado')], default='p', max_length=1, verbose_name='Status da demanda'),
        ),
        migrations.CreateModel(
            name='Painel_Acompanhamento_Demandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do painel')),
                ('hash', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Hash do painel')),
                ('servidores', models.ManyToManyField(blank=True, related_name='painel_acompanhamento', to='instituicoes.servidor')),
                ('user_inclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
        ),
    ]
