# Generated by Django 4.2.16 on 2025-06-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0028_alter_demandas_prioridade_alter_demandas_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Média'), (2, 'Importante'), (0, 'Regular'), (3, 'Urgente')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('a', 'Gestão de Projetos'), ('p', 'Ação planejada'), ('t', 'Gestão de Projetos'), ('n', 'Nenhuma')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='status',
            field=models.CharField(choices=[('x', 'Cancelado'), ('p', 'Em aberto'), ('e', 'Em andamento'), ('c', 'Concluído')], default='p', max_length=1, verbose_name='Status da demanda'),
        ),
    ]
