# Generated by Django 4.2.16 on 2025-06-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0030_alter_demandas_prioridade_alter_demandas_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(3, 'Urgente'), (1, 'Média'), (2, 'Importante'), (0, 'Regular')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('p', 'Ação planejada'), ('n', 'Nenhuma'), ('a', 'Gestão de Projetos'), ('t', 'Gestão de Projetos')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='status',
            field=models.CharField(choices=[('e', 'Em andamento'), ('c', 'Concluído'), ('p', 'Em aberto'), ('x', 'Cancelado')], default='p', max_length=1, verbose_name='Status da demanda'),
        ),
    ]
