# Generated by Django 4.2.16 on 2025-06-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0031_alter_demandas_prioridade_alter_demandas_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(2, 'Importante'), (3, 'Urgente'), (0, 'Regular'), (1, 'Média')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('t', 'Gestão de Projetos'), ('p', 'Ação planejada'), ('a', 'Gestão de Projetos'), ('n', 'Nenhuma')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='status',
            field=models.CharField(choices=[('e', 'Em andamento'), ('x', 'Cancelado'), ('p', 'Em aberto'), ('c', 'Concluído')], default='p', max_length=1, verbose_name='Status da demanda'),
        ),
    ]
