# Generated by Django 4.2.16 on 2025-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0033_alter_demandas_prioridade_alter_demandas_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Média'), (3, 'Urgente'), (2, 'Importante'), (0, 'Regular')], default=0),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='referencia',
            field=models.CharField(choices=[('a', 'Gestão de Projetos'), ('p', 'Ação planejada'), ('n', 'Nenhuma'), ('t', 'Gestão de Projetos')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='status',
            field=models.CharField(choices=[('e', 'Em andamento'), ('p', 'Em aberto'), ('x', 'Cancelado'), ('c', 'Concluído')], default='p', max_length=1, verbose_name='Status da demanda'),
        ),
    ]
