# Generated by Django 4.2.11 on 2025-06-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projetos",
            "0035_alter_demandas_prioridade_alter_demandas_referencia_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandas",
            name="prioridade",
            field=models.IntegerField(
                choices=[
                    (2, "Importante"),
                    (0, "Regular"),
                    (1, "Média"),
                    (3, "Urgente"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="demandas",
            name="referencia",
            field=models.CharField(
                choices=[
                    ("p", "Ação planejada"),
                    ("a", "Gestão de Projetos"),
                    ("n", "Nenhuma"),
                    ("t", "Gestão de Projetos"),
                ],
                default="n",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="demandas",
            name="status",
            field=models.CharField(
                choices=[
                    ("p", "Em aberto"),
                    ("c", "Concluído"),
                    ("x", "Cancelado"),
                    ("e", "Em andamento"),
                ],
                default="p",
                max_length=1,
                verbose_name="Status da demanda",
            ),
        ),
    ]
