# Generated by Django 4.2.20 on 2025-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_alter_alocaitem_item_alter_alocaitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoitem',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicoitem',
            name='usuario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
