# Generated by Django 4.2.20 on 2025-05-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_alter_alocaitem_item_alter_alocaitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoitem',
            name='tipo',
            field=models.CharField(choices=[('ALOCACAO', 'Alocação'), ('RETIRADA', 'Retirada'), ('ADICAO', 'Adição')], max_length=10),
        ),
    ]
