# Generated by Django 4.2.11 on 2025-05-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_alter_historicoitem_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
