# Generated by Django 4.2.16 on 2025-02-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('protocol', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
