# Generated by Django 4.2.16 on 2025-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_logwatcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('level', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('tid', models.IntegerField()),
                ('client_ip', models.GenericIPAddressField()),
                ('client_port', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ApacheLog',
            new_name='ApacheAccessLog',
        ),
    ]
