# Generated by Django 4.2.11 on 2024-03-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='downloads/icons/', verbose_name='Imagem'),
        ),
    ]
