# Generated by Django 4.2.11 on 2024-03-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0002_downloads_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemas',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='downloads/icons/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='tiposistema',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='downloads/icons/', verbose_name='Imagem'),
        ),
    ]
