# Generated by Django 4.2.11 on 2024-03-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0003_sistemas_imagem_tiposistema_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodownload',
            options={'verbose_name': 'Tipo de Download', 'verbose_name_plural': 'Tipos de Download'},
        ),
        migrations.AlterModelOptions(
            name='tiposistema',
            options={'verbose_name': 'Tipo de Sistemas', 'verbose_name_plural': 'Tipos de Sistemas'},
        ),
        migrations.AddField(
            model_name='tiposistema',
            name='slug',
            field=models.SlugField(default='', max_length=64, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
