# Generated by Django 4.2.11 on 2024-09-03 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=164, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
                ('palavras_chave', models.CharField(max_length=164, verbose_name='Palavras chaves')),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
            },
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=164, verbose_name='Tema')),
                ('tipo', models.CharField(choices=[('ytb', 'youtube'), ('pdf', 'pdf')], max_length=3, verbose_name='Tipo')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base_conhecimento.topico', verbose_name='Tópico associado')),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo_GoogleDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.TextField(verbose_name='HTML do iframe')),
                ('subtopico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base_conhecimento.subtopico', verbose_name='Subtópico Associado')),
            ],
        ),
    ]
