# Generated by Django 4.2.11 on 2024-10-22 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0003_alter_subtopico_tipo_arquivo_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo_PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Título')),
                ('arquivo_pdf', models.FileField(upload_to='pdfs/', verbose_name='Arquivo PDF')),
                ('subtopico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base_conhecimento.subtopico', verbose_name='Subtópico Associado')),
            ],
        ),
    ]
