# Generated by Django 4.2.11 on 2024-10-22 18:20

import base_conhecimento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0004_arquivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo_pdf',
            name='arquivo_pdf',
            field=models.FileField(upload_to=base_conhecimento.models.PathAndRename('pdfs/'), verbose_name='Arquivo PDF'),
        ),
    ]
