# Generated by Django 5.0.3 on 2024-03-19 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('contato', models.CharField(default='Telefone', max_length=11)),
                ('email', models.EmailField(default='', max_length=254)),
                ('matricula', models.CharField(default='', max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(default='Telefone', max_length=11)),
                ('assunto', models.CharField(max_length=150)),
                ('prioridade', models.CharField(choices=[('0', 'Baixa'), ('1', 'Média'), ('2', 'Alta')], default='0', max_length=1)),
                ('status', models.CharField(choices=[('0', 'Aberto'), ('1', 'Pendente'), ('2', 'Finalizado')], default='0', max_length=1)),
                ('descricao', models.TextField(default='')),
                ('dataAbertura', models.DateTimeField(auto_now_add=True)),
                ('dataFechamento', models.DateTimeField(null=True)),
                ('numero', models.CharField(default=0, max_length=10)),
                ('anexo', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('requisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitante', to='chamados.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, verbose_name='Nome do Serviço')),
                ('sigla', models.CharField(blank=True, max_length=3, verbose_name='Sigla')),
                ('descricao', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('servidor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chamados.servidor')),
                ('tipo', models.ManyToManyField(to='chamados.tipo', verbose_name='Tipo')),
            ],
            bases=('chamados.servidor',),
        ),
        migrations.CreateModel(
            name='OSImpressora',
            fields=[
                ('chamado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chamados.chamado')),
                ('serie', models.CharField(max_length=8)),
                ('contador', models.PositiveIntegerField()),
            ],
            bases=('chamados.chamado',),
        ),
        migrations.CreateModel(
            name='OSInternet',
            fields=[
                ('chamado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chamados.chamado')),
                ('nofcip', models.CharField(max_length=8)),
            ],
            bases=('chamados.chamado',),
        ),
        migrations.CreateModel(
            name='OSSistema',
            fields=[
                ('chamado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chamados.chamado')),
                ('sistema', models.CharField(max_length=50)),
            ],
            bases=('chamados.chamado',),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField(default='')),
                ('confidencial', models.BooleanField(default=False)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado', verbose_name='Chamado')),
                ('quemComentou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.servidor', verbose_name='quemComentou')),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.secretaria', verbose_name='Secretaria'),
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('cep', models.CharField(default='', max_length=8)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('logradouro', models.CharField(default='', max_length=150)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.secretaria', verbose_name='Secretaria')),
            ],
        ),
        migrations.AddField(
            model_name='servidor',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.tipo'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='atendente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendente', to='chamados.atendente', verbose_name='Atendente'),
        ),
    ]
