# Generated by Django 5.0.3 on 2024-03-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='osimpressora',
            options={'verbose_name': 'Ordem de Serviço - Impressora', 'verbose_name_plural': 'Ordens de Serviço - Impressora'},
        ),
        migrations.AlterModelOptions(
            name='osinternet',
            options={'verbose_name': 'Ordem de Serviço - Internet', 'verbose_name_plural': 'Ordens de Serviço - Internet'},
        ),
        migrations.AlterModelOptions(
            name='ossistemas',
            options={'verbose_name': 'Ordem de Serviço - Sistemas', 'verbose_name_plural': 'Ordens de Serviço - Sistemas'},
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='servidor',
        ),
        migrations.RemoveField(
            model_name='ossistemas',
            name='versao',
        ),
    ]
