# Generated by Django 5.0.3 on 2024-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_alter_chamado_options_alter_mensagem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('', 'Não definida'), ('0', 'Baixa'), ('1', 'Média'), ('2', 'Alta')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('0', 'Aberto'), ('2', 'Em atendimento'), ('1', 'Pendente'), ('3', 'Fechado'), ('4', 'Finalizado')], default='', max_length=1),
        ),
    ]
