# Generated by Django 5.0.3 on 2024-03-20 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_alter_chamado_prioridade_alter_chamado_status'),
        ('instituicoes', '0005_servidor_user_alter_servidor_user_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='anexo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='chamados/anexos/', verbose_name='Possui alguma foto ou print do problema? Caso sim, anexe-a abaixo.'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='assunto',
            field=models.CharField(max_length=64, verbose_name='Assunto do chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição do problema'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('', 'Não definida'), ('0', 'Baixa'), ('1', 'Média'), ('2', 'Alta')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='requisitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitante_chamados', to='instituicoes.servidor', verbose_name='Para quem é o chamado?'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.setor', verbose_name='Para qual secretaria é o chamado?'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('0', 'Aberto'), ('2', 'Em atendimento'), ('1', 'Pendente'), ('3', 'Fechado'), ('4', 'Finalizado')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='telefone',
            field=models.CharField(max_length=14, verbose_name='Qual telefone para contato?'),
        ),
        migrations.AlterField(
            model_name='osimpressora',
            name='chamado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado', verbose_name='Chamado'),
        ),
        migrations.AlterField(
            model_name='osinternet',
            name='chamado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado', verbose_name='Chamado'),
        ),
        migrations.AlterField(
            model_name='ossistemas',
            name='chamado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado', verbose_name='Chamado'),
        ),
    ]
