# Generated by Django 5.0.3 on 2024-03-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_alter_chamado_anexo_alter_chamado_assunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de ultima atualização'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='dt_execucao',
            field=models.DateField(null=True, verbose_name='Data da execução do chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='dt_fechamento',
            field=models.DateTimeField(null=True, verbose_name='Data do fechamaneto do chamado'),
        ),
    ]
