# Generated by Django 4.2.11 on 2024-03-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0005_servidor_user_alter_servidor_user_inclusao'),
        ('chamados', '0005_alter_chamado_dt_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.setor', verbose_name='Para qual setor é o chamado?'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('0', 'Aberto'), ('1', 'Em atendimento'), ('2', 'Pendente'), ('3', 'Fechado'), ('4', 'Finalizado')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='osimpressora',
            name='chamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado', verbose_name='Chamado'),
        ),
        migrations.AlterField(
            model_name='osinternet',
            name='chamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado', verbose_name='Chamado'),
        ),
        migrations.AlterField(
            model_name='ossistemas',
            name='chamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado', verbose_name='Chamado'),
        ),
    ]
