# Generated by Django 4.2.11 on 2024-03-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_alter_chamado_setor_alter_chamado_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osinternet',
            name='nofcip',
            field=models.CharField(max_length=64, verbose_name='NOFCIP'),
        ),
    ]
