# Generated by Django 4.2.11 on 2024-03-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_alter_osinternet_nofcip'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='dt_inicio_execucao',
            field=models.DateTimeField(null=True, verbose_name='Data do inicio da execução do chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='dt_execucao',
            field=models.DateTimeField(null=True, verbose_name='Data o fim daa execução do chamado'),
        ),
    ]
