# Generated by Django 4.2.11 on 2024-03-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_chamado_dt_inicio_execucao_alter_chamado_dt_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendente',
            name='nivel',
            field=models.CharField(choices=[('0', 'Nível 0 - Help Desk'), ('1', 'Nível 1 - Suporte Técnico'), ('2', 'Nível 2 - Administração')], default='0', max_length=1),
        ),
    ]
