# Generated by Django 4.2.11 on 2024-03-25 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_atendente_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSTelefonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramal', models.CharField(max_length=20, verbose_name='Ramal')),
                ('chamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado', verbose_name='Chamado')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço - Telefonia',
                'verbose_name_plural': 'Ordens de Serviço - Telefonia',
            },
        ),
    ]
