# Generated by Django 4.2.11 on 2024-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_alter_atendente_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoPreferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Período Preferencial',
                'verbose_name_plural': 'Períodos Preferenciais',
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='dt_agendamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data agendada para o atendimento'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='periodo_preferencial',
            field=models.ManyToManyField(to='chamados.periodopreferencial', verbose_name='Período preferencial'),
        ),
    ]
