# Generated by Django 4.2.11 on 2024-05-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0012_alter_servidor_user_inclusao'),
        ('chamados', '0012_periodopreferencial_chamado_dt_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='dt_execucao',
            field=models.DateTimeField(null=True, verbose_name='Data o fim da execução do chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='periodo_preferencial',
            field=models.ManyToManyField(to='chamados.periodopreferencial', verbose_name='Escolha o período que você pode ser atendido'),
        ),
        migrations.CreateModel(
            name='Pausas_Execucao_do_Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateTimeField(verbose_name='Data de início da pausa')),
                ('dt_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de fim da pausa')),
                ('motivo', models.TextField(verbose_name='Motivo da pausa')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado', verbose_name='Chamado')),
                ('user_inclusao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_inclusao_pausas', to='instituicoes.servidor', verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Pausa na execução do chamado',
                'verbose_name_plural': 'Pausas na execução do chamado',
            },
        ),
    ]
