# Generated by Django 4.2.11 on 2024-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0013_alter_chamado_dt_execucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pausas_execucao_do_chamado',
            name='motivo',
            field=models.TextField(null=True, verbose_name='Motivo da pausa'),
        ),
    ]
