# Generated by Django 4.2.11 on 2024-05-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0012_alter_servidor_user_inclusao'),
        ('chamados', '0014_alter_pausas_execucao_do_chamado_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pausas_execucao_do_chamado',
            name='user_fim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_finalizacao_pausas', to='instituicoes.servidor', verbose_name='Usuário de finalização'),
        ),
    ]
