# Generated by Django 4.2.11 on 2024-05-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0012_alter_servidor_user_inclusao'),
        ('chamados', '0015_pausas_execucao_do_chamado_user_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pausas_execucao_do_chamado',
            name='user_fim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_finalizacao_pausas', to='instituicoes.servidor', verbose_name='Usuário de finalização'),
        ),
        migrations.AlterField(
            model_name='pausas_execucao_do_chamado',
            name='user_inclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_inclusao_pausas', to='instituicoes.servidor', verbose_name='Usuário de inclusão'),
        ),
    ]
