# Generated by Django 4.2.11 on 2024-09-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0012_alter_servidor_user_inclusao'),
        ('chamados', '0017_alter_pausas_execucao_do_chamado_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='endereco',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='requisitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitante_chamados', to='instituicoes.servidor', verbose_name='Nome'),
        ),
    ]
