# Generated by Django 4.2.11 on 2024-09-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0018_chamado_endereco_alter_chamado_requisitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osimpressora',
            name='contador',
            field=models.IntegerField(null=True, verbose_name='Contador'),
        ),
        migrations.AlterField(
            model_name='osimpressora',
            name='n_serie',
            field=models.CharField(max_length=64, null=True, verbose_name='Número de série'),
        ),
        migrations.AlterField(
            model_name='osinternet',
            name='nofcip',
            field=models.CharField(max_length=64, null=True, verbose_name='NOFCIP'),
        ),
    ]
