# Generated by Django 4.2.11 on 2024-09-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0019_alter_osimpressora_contador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='requisitante',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
