# Generated by Django 4.2.11 on 2024-10-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0023_alter_chamado_prioridade_alter_chamado_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Qual telefone para contato?'),
        ),
    ]
