# Generated by Django 4.2.11 on 2024-10-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0015_alter_servidor_telefone'),
        ('chamados', '0024_alter_chamado_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.secretaria', verbose_name='Para qual setor é o chamado?'),
        ),
    ]
