# Generated by Django 4.2.11 on 2024-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0025_chamado_secretaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('0', 'Aberto'), ('2', 'Pendente'), ('4', 'Finalizado')], default='0', max_length=1),
        ),
    ]
