# Generated by Django 4.2.16 on 2024-11-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0016_alter_servidor_matricula'),
        ('chamados', '0026_alter_chamado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atendente', to='chamados.atendente', verbose_name='Atendente'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='dt_execucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data o fim da execução do chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='dt_inicio_execucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do inicio da execução do chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.setor', verbose_name='Para qual setor é o chamado?'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='user_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_atualizacao_chamados', to='instituicoes.servidor', verbose_name='Usuário da ultima atualização'),
        ),
    ]
