# Generated by Django 4.2.16 on 2024-11-22 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamados', '0027_alter_chamado_atendente_alter_chamado_dt_execucao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_Designados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_designacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de designação')),
                ('atendente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamados.atendente', verbose_name='Atendente')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado', verbose_name='Chamado')),
                ('user_inclusao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Histórico de designados',
                'verbose_name_plural': 'Histórico de designados',
            },
        ),
    ]
