# Generated by Django 4.2.16 on 2024-11-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0028_historico_designados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='dt_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do fechamaneto do chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='periodo_preferencial',
            field=models.ManyToManyField(blank=True, to='chamados.periodopreferencial', verbose_name='Escolha o período que você pode ser atendido'),
        ),
    ]
