# Generated by Django 4.2.16 on 2024-11-28 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamados', '0029_alter_chamado_dt_fechamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='mesclado',
            field=models.BooleanField(default=False, verbose_name='Chamado mesclado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do cancelamento'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('0', 'Aberto'), ('2', 'Pendente'), ('4', 'Finalizado'), ('5', 'Cancelado')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='Historico_Mesclagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_mesclagem', models.DateTimeField(auto_now_add=True, verbose_name='Data de mesclagem')),
                ('chamado_resultante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamado_resultante', to='chamados.chamado', verbose_name='Chamado resultante da mesclagem')),
                ('chamados_mesclados', models.ManyToManyField(related_name='chamados_mesclados', to='chamados.chamado', verbose_name='Chamados mesclados')),
                ('user_inclusao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Histórico de mesclagem',
                'verbose_name_plural': 'Histórico de mesclagens',
            },
        ),
    ]
