# Generated by Django 4.2.16 on 2024-12-03 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamados', '0030_chamado_mesclado_chamado_motivo_cancelamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='endereco',
            field=models.CharField(max_length=250, null=True, verbose_name='Endereço'),
        ),
        migrations.CreateModel(
            name='SubTipoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=164, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.tipochamado', verbose_name='Tipo de chamado')),
                ('user_inclusao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Subtipo de Chamado',
                'verbose_name_plural': 'Subtipos de Chamados',
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='subtipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamados.subtipochamado', verbose_name='Subtipo chamado'),
        ),
    ]
