# Generated by Django 4.2.16 on 2024-12-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0031_alter_chamado_endereco_subtipochamado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='relatorio',
            field=models.TextField(null=True, verbose_name='Relatório do chamado'),
        ),
    ]
