# Generated by Django 4.2.11 on 2024-12-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0032_chamado_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='relatorio',
            field=models.TextField(null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('0', 'Aberto'), ('2', 'Pendente'), ('4', 'Finalizado'), ('5', 'Cancelado'), ('6', 'Mesclado')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='subtipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamados.subtipochamado', verbose_name='Serviços realizado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamados.tipochamado', verbose_name='Grupo do chamado'),
        ),
    ]
