# Generated by Django 4.2.16 on 2025-01-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0033_alter_chamado_relatorio_alter_chamado_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chamadoSatisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(choices=[('0', 'Totalmente insatisfeito'), ('1', 'Insatisfeito'), ('2', 'Neutro'), ('3', 'Satisfeito'), ('4', 'Extremamente satisfeito')], max_length=1, null=True, verbose_name='Satisfação')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data de inclusão')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado', verbose_name='Chamado')),
            ],
            options={
                'verbose_name': 'Satisfação do atendimento',
                'verbose_name_plural': 'Satisfações dos atendimentos',
            },
        ),
    ]
