# Generated by Django 4.2.16 on 2025-01-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0034_chamadosatisfacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='pesquisa_satisfacao',
            field=models.BooleanField(default=True, verbose_name='Pesquisa de satisfação'),
            preserve_default=False,
        ),
    ]
