# Generated by Django 4.2.16 on 2025-01-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0035_chamado_pesquisa_satisfacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='pesquisa_satisfacao',
            field=models.BooleanField(default=False, verbose_name='Pesquisa de satisfação'),
        ),
    ]
