# Generated by Django 4.2.16 on 2025-01-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0036_alter_chamado_pesquisa_satisfacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadosatisfacao',
            name='avaliacao_justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da avaliação'),
        ),
        migrations.AddField(
            model_name='chamadosatisfacao',
            name='cordialidade',
            field=models.CharField(choices=[('0', 'Ruim'), ('1', 'Regular'), ('2', 'Bom'), ('3', 'Ótimo'), ('4', 'Excelente')], max_length=1, null=True, verbose_name='Como foi a cordialidade e educação do nosso técnico?'),
        ),
        migrations.AddField(
            model_name='chamadosatisfacao',
            name='cordialidade_justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da cordialidade'),
        ),
        migrations.AddField(
            model_name='chamadosatisfacao',
            name='receberia_novamente_o_tecnico',
            field=models.CharField(choices=[('n', 'Não'), ('s', 'Sim'), ('i', 'Indiferente')], max_length=1, null=True, verbose_name='Você receberia novamente o mesmo técnico?'),
        ),
        migrations.AddField(
            model_name='chamadosatisfacao',
            name='resolucao',
            field=models.CharField(choices=[('0', 'Ruim'), ('1', 'Regular'), ('2', 'Bom'), ('3', 'Ótimo'), ('4', 'Excelente')], max_length=2, null=True, verbose_name='O problema foi resolvido de forma satisfatória?'),
        ),
        migrations.AlterField(
            model_name='chamadosatisfacao',
            name='avaliacao',
            field=models.CharField(choices=[('0', 'Ruim'), ('1', 'Regular'), ('2', 'Bom'), ('3', 'Ótimo'), ('4', 'Excelente')], max_length=1, null=True, verbose_name='Qual sua avaliação geral sobre o atendimento do técnico?'),
        ),
        migrations.AlterField(
            model_name='chamadosatisfacao',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Você possui alguma sugestão para melhorar o nosso serviço?'),
        ),
    ]
