# Generated by Django 4.2.16 on 2025-01-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0037_chamadosatisfacao_avaliacao_justificativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadosatisfacao',
            name='resolucao',
            field=models.CharField(choices=[('sc', 'Sim, completamente'), ('sp', 'Sim, parcialmente'), ('n', 'Não')], max_length=2, null=True, verbose_name='O problema foi resolvido de forma satisfatória?'),
        ),
    ]
