# Generated by Django 4.2.16 on 2025-02-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0040_chamado_criado_pelo_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='criado_pelo_servidor',
            field=models.CharField(choices=[('0', 'Não'), ('1', 'Sim'), ('2', 'Origem desconhecida')], default='2', max_length=1),
        ),
    ]
