# Generated by Django 4.2.16 on 2024-12-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagem_capa', models.ImageField(upload_to='noticias/')),
                ('alt_capa', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('destaque', models.BooleanField(default=False)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
