# Generated by Django 4.2.16 on 2024-12-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticias_link_noticias_resumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='link',
        ),
        migrations.AddField(
            model_name='carrousell',
            name='link',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
