# Generated by Django 4.2.16 on 2025-03-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_remove_noticias_link_carrousell_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
