# Generated by Django 4.2.16 on 2025-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticias_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(default='', max_length=100)),
                ('imagem', models.ImageField(upload_to='noticias/imagens/')),
            ],
        ),
    ]
