# Generated by Django 4.2.11 on 2024-03-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicoes', '0002_alter_secretaria_options_alter_setor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=4, verbose_name='Número')),
                ('webex', models.CharField(max_length=64, verbose_name='Webex')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.secretaria', verbose_name='Secretaria')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Ramal',
                'verbose_name_plural': 'Ramais',
            },
        ),
    ]
