# Generated by Django 4.2.11 on 2024-03-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='webex',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Webex'),
        ),
    ]
