# Generated by Django 4.2.11 on 2024-03-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0002_alter_ramal_webex'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramal',
            name='referencia',
            field=models.CharField(default='', max_length=64, verbose_name='Referência'),
            preserve_default=False,
        ),
    ]
