# Generated by Django 4.2.11 on 2024-03-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0003_ramal_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramal',
            name='responsavel',
            field=models.CharField(blank=True, max_length=164, null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='ramal',
            name='referencia',
            field=models.CharField(max_length=164, verbose_name='Referência'),
        ),
    ]
