# Generated by Django 4.2.11 on 2024-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0004_ramal_responsavel_alter_ramal_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='numero',
            field=models.CharField(max_length=5, verbose_name='Número'),
        ),
    ]
