# Generated by Django 4.2.11 on 2024-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0005_alter_ramal_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='responsavel',
            field=models.CharField(default=1, max_length=164, verbose_name='Responsável'),
            preserve_default=False,
        ),
    ]
