# Generated by Django 4.2.11 on 2024-03-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0006_alter_ramal_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramal',
            name='webex',
        ),
    ]
