# Generated by Django 4.2.11 on 2024-03-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0005_servidor_user_alter_servidor_user_inclusao'),
        ('telefonia', '0007_remove_ramal_webex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefonista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=164, verbose_name='Nome')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
                ('servidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidor_telefonista', to='instituicoes.servidor', verbose_name='Servidor')),
                ('user_inclusao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.servidor', verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Telefonista',
                'verbose_name_plural': 'Telefonistas',
            },
        ),
    ]
