# Generated by Django 4.2.16 on 2025-01-16 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicoes', '0016_alter_servidor_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=200)),
                ('entrada1', models.TimeField()),
                ('saida1', models.TimeField(blank=True, null=True)),
                ('entrada2', models.TimeField(blank=True, null=True)),
                ('saida2', models.TimeField(blank=True, null=True)),
                ('data_registro', models.DateField()),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituicoes.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituicoes.setor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
