# Generated by Django 4.2.16 on 2025-01-20 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0016_alter_servidor_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle_de_ponto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geral', models.BooleanField(default=False)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituicoes.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituicoes.setor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
