# Generated by Django 4.2.16 on 2025-02-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_ponto', '0003_registro_ip_inclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='pode_alterar_registro',
            field=models.BooleanField(default=False),
        ),
    ]
