# Generated by Django 4.2.16 on 2025-02-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_ponto', '0004_responsavel_pode_alterar_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Alteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada1_old', models.TimeField(blank=True, null=True, verbose_name='Entrada 1 antiga')),
                ('entrada1', models.TimeField(blank=True, null=True, verbose_name='Entrada 1 nova')),
                ('saida1_old', models.TimeField(blank=True, null=True, verbose_name='Saída 1 antiga')),
                ('saida1', models.TimeField(blank=True, null=True, verbose_name='Saída 1 nova')),
                ('entrada2_old', models.TimeField(blank=True, null=True, verbose_name='Entrada 2 antiga')),
                ('entrada2', models.TimeField(blank=True, null=True, verbose_name='Entrada 2 nova')),
                ('saida2_old', models.TimeField(blank=True, null=True, verbose_name='Saída 2 antiga')),
                ('saida2', models.TimeField(blank=True, null=True, verbose_name='Saída 2 nova')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data da alteração')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_de_ponto.registro', verbose_name='Registro alterado')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_de_ponto.responsavel', verbose_name='Responsável pela alteração')),
            ],
        ),
    ]
