# Generated by Django 4.2.11 on 2024-03-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormIndicacaoComitePSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretaria', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do representante')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matrícula do representante')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do representante')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone do representante')),
                ('observação', models.TextField(verbose_name='Caso deseja fazer alguma observação, escreva aqui:')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
