# Generated by Django 4.2.11 on 2024-03-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formindicacaocomitepsp',
            name='observação',
            field=models.TextField(verbose_name='Possui alguma sugestão para pauta da comissão?'),
        ),
    ]
