# Generated by Django 4.2.11 on 2024-07-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0003_cadastrowebex'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSugestaoSemanaNacionalCET2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sugestao', models.TextField()),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
