# Generated by Django 4.2.11 on 2024-07-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0004_formsugestaosemananacionalcet2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsugestaosemananacionalcet2024',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Seu email'),
        ),
        migrations.AlterField(
            model_name='formsugestaosemananacionalcet2024',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Seu nome completo'),
        ),
        migrations.AlterField(
            model_name='formsugestaosemananacionalcet2024',
            name='sugestao',
            field=models.TextField(verbose_name='Deixe sua sugestão e possíveis contatos para a SNCT 2024'),
        ),
        migrations.AlterField(
            model_name='formsugestaosemananacionalcet2024',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Seu whatsapp'),
        ),
    ]
