# Generated by Django 4.2.11 on 2024-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0006_cadastroel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistemas_EL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cadastroel',
            name='sistemas',
        ),
        migrations.AddField(
            model_name='cadastroel',
            name='sistemas',
            field=models.ManyToManyField(to='formfacil.sistemas_el', verbose_name='Quais sistemas você precisa de acesso?'),
        ),
    ]
