# Generated by Django 4.2.11 on 2024-08-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0007_sistemas_el_remove_cadastroel_sistemas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroel',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
