# Generated by Django 4.2.15 on 2024-08-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0008_cadastroel_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroel',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cadastroel',
            name='telefone',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cadastroel',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Deseja fazer alguma observação?'),
        ),
    ]
