# Generated by Django 4.2.11 on 2024-08-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0009_cadastroel_email_cadastroel_telefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcao_Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(max_length=50, verbose_name='Dia da semana')),
                ('dia_do_mes', models.CharField(max_length=2, verbose_name='Dia do mês')),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro_Aulas_Processo_Digital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matrícula')),
                ('secretaria', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15, verbose_name='Seu telefone')),
                ('turma_escolhida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formfacil.opcao_turmas', verbose_name='Turma escolhida')),
            ],
        ),
    ]
