# Generated by Django 4.2.11 on 2024-08-27 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0011_opcao_turmas_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_aulas_processo_digital',
            name='dt_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro_aulas_processo_digital',
            name='matricula',
            field=models.CharField(max_length=6, verbose_name='Matrícula'),
        ),
    ]
