# Generated by Django 4.2.11 on 2024-09-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0014_alter_cadastro_aulas_processo_digital_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Aulas_Treinamento_Tributario_Contadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('matricula', models.CharField(blank=True, max_length=6, verbose_name='Matrícula')),
                ('secretaria', models.CharField(max_length=250)),
                ('setor', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=15, verbose_name='Seu telefone')),
                ('dt_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro_Aulas_Treinamento_Tributario_Emissores_Taxas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('matricula', models.CharField(blank=True, max_length=6, verbose_name='Matrícula')),
                ('secretaria', models.CharField(max_length=250)),
                ('setor', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=15, verbose_name='Seu telefone')),
                ('dt_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
