# Generated by Django 4.2.11 on 2024-09-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0015_cadastro_aulas_treinamento_tributario_contadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_aulas_treinamento_tributario_contadores',
            name='cpf',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cadastro_aulas_treinamento_tributario_emissores_taxas',
            name='cpf',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
