# Generated by Django 4.2.11 on 2024-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0016_cadastro_aulas_treinamento_tributario_contadores_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_aulas_treinamento_tributario_contadores',
            name='telefone',
            field=models.CharField(max_length=16, verbose_name='Seu telefone'),
        ),
    ]
