# Generated by Django 4.2.11 on 2024-10-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0017_alter_cadastro_aulas_treinamento_tributario_contadores_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_aulas_treinamento_tributario_contadores',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Seu telefone'),
        ),
    ]
