# Generated by Django 4.2.16 on 2024-12-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0018_alter_cadastro_aulas_treinamento_tributario_contadores_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao_Decretos_Portaria_E_Atos_Do_Prefeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(blank=True, max_length=6, verbose_name='Matrícula')),
                ('secretaria', models.CharField(max_length=250)),
                ('setor', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=15, verbose_name='Seu telefone')),
                ('horarios', models.CharField(choices=[('14:00', '14:00'), ('16:00', '16:00')], max_length=5, verbose_name='Horários disponíveis')),
                ('dt_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
