# Generated by Django 4.2.11 on 2024-12-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0018_alter_cadastro_aulas_treinamento_tributario_contadores_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcao_Turmas_Decretos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(max_length=50, verbose_name='Dia da semana')),
                ('dia_do_mes', models.CharField(max_length=2, verbose_name='Dia do mês')),
                ('hora', models.TimeField()),
                ('ativo', models.BooleanField(default=True, verbose_name='Opcao de turma ainda aberta?')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao_Decretos_Portaria_Atos_Prefeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(blank=True, max_length=6, verbose_name='Matrícula')),
                ('secretaria', models.CharField(max_length=250)),
                ('setor', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=15, verbose_name='Seu telefone')),
                ('dt_registro', models.DateTimeField(auto_now_add=True)),
                ('turma_escolhida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formfacil.opcao_turmas_decretos', verbose_name='Selecione uma turma')),
            ],
        ),
    ]
