# Generated by Django 4.2.16 on 2025-03-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0019_inscricao_decretos_portaria_e_atos_do_prefeito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_de_Almoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_requisitante', models.CharField(max_length=150, verbose_name='Nome de quem pode requisitar')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matrícula')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('secretaria', models.CharField(max_length=250, verbose_name='Secretaria')),
                ('autorizador', models.CharField(max_length=150, verbose_name='Quem autoriza a solicitação')),
                ('responsavel_material', models.CharField(max_length=150, verbose_name='Quem pega os materiais')),
                ('dt_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
