# Generated by Django 4.2.11 on 2024-12-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0019_opcao_turmas_decretos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcao_turmas_decretos',
            old_name='hora',
            new_name='hora_inicio',
        ),
    ]
