# Generated by Django 4.2.16 on 2025-03-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0020_cadastro_de_almoxarifado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoSistemaEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(max_length=100, verbose_name='Sistema Avaliado')),
                ('usuario_nome', models.CharField(max_length=150, verbose_name='Nome do Usuário')),
                ('usuario_matricula', models.CharField(max_length=10, verbose_name='Matrícula do Usuário')),
                ('satisfacao', models.IntegerField(blank=True, null=True, verbose_name='Nível de Satisfação (1 a 5)')),
                ('houve_lentidao', models.IntegerField(blank=True, null=True, verbose_name='Já houve algum problema?')),
                ('sugestao', models.TextField(blank=True, null=True, verbose_name='Sugestão')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('usuario_inclusao', models.CharField(blank=True, max_length=150, verbose_name='Usuário que incluiu')),
            ],
        ),
    ]
