# Generated by Django 4.2.16 on 2025-03-27 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formfacil', '0021_avaliacaosistemael'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaosistemael',
            name='usuario_inclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que incluiu'),
        ),
    ]
