# Generated by Django 4.2.16 on 2025-03-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0022_alter_avaliacaosistemael_usuario_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaosistemael',
            name='houve_lentidao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Avaliação o tempo de resposta do sistema '),
        ),
    ]
