# Generated by Django 4.2.16 on 2025-04-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0023_alter_avaliacaosistemael_houve_lentidao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoEmailInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matrícula')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('secretaria', models.CharField(max_length=250, verbose_name='Secretaria')),
                ('email_institucional', models.EmailField(max_length=254, verbose_name='E-mail institucional sugerido')),
                ('dt_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
