# Generated by Django 4.2.16 on 2025-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0024_solicitacaoemailinstitucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoemailinstitucional',
            name='telefone',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='solicitacaoemailinstitucional',
            name='email_institucional',
            field=models.EmailField(max_length=254, verbose_name='E-mail institucional sugerido. Sugestão no formato: nome.sobrenome@prefeituradenovafriburgo.rj.gov.br'),
        ),
    ]
