# Generated by Django 4.2.11 on 2025-05-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0025_solicitacaoemailinstitucional_telefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadronizacaoPagamentoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matrícula')),
                ('secretaria', models.CharField(max_length=250)),
                ('setor', models.CharField(max_length=250)),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('turma', models.CharField(choices=[('turma1', 'Turma 1 (10h às 12h)'), ('turma2', 'Turma 2 (14h às 16h)')], max_length=10)),
                ('dt_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoDigitalInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matrícula')),
                ('secretaria', models.CharField(max_length=250)),
                ('setor', models.CharField(max_length=250)),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('turma', models.CharField(choices=[('turma1', 'Turma 1 (10h às 12h)'), ('turma2', 'Turma 2 (14h às 16h)')], max_length=10)),
                ('dt_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
