# Generated by Django 4.2.16 on 2025-06-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfacil', '0026_padronizacaopagamentoinscricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padronizacaopagamentoinscricao',
            name='turma',
            field=models.CharField(choices=[('turma1', 'Turma 1 (10h às 12h | 04/06/2025)'), ('turma2', 'Turma 2 (14h às 16h | 04/06/2025)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='processodigitalinscricao',
            name='turma',
            field=models.CharField(choices=[('turma1', 'Turma 1 (10h às 12h | 03/06/2025)'), ('turma2', 'Turma 2 (14h às 16h | 03/06/2025)'), ('turma3', 'Turma 3 (10h às 12h | 05/06/2025)')], max_length=10),
        ),
        migrations.DeleteModel(
            name='CadastroEL',
        ),
    ]
