# Generated by Django 4.2.11 on 2025-06-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formfacil", "0027_alter_padronizacaopagamentoinscricao_turma_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SistemaGPIparaContadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome Completo"),
                ),
                ("cpf", models.CharField(max_length=14, verbose_name="CPF")),
                ("telefone", models.CharField(max_length=15, verbose_name="Telefone")),
                (
                    "empresa",
                    models.CharField(
                        max_length=150, verbose_name="Nome da Empresa de contabilidade"
                    ),
                ),
                ("dt_inscricao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
