# Generated by Django 4.2.11 on 2025-06-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formfacil", "0028_sistemagpiparacontadores"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistemagpiparacontadores",
            name="turma",
            field=models.CharField(
                choices=[
                    ("turma1", "Turma 1 (10h às 12h | 04/07/2025)"),
                    ("turma2", "Turma 2 (14h às 16h | 04/07/2025)"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
