# Generated by Django 4.2.11 on 2024-03-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretaria',
            options={'verbose_name': 'Secretaria', 'verbose_name_plural': 'Secretarias'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
