# Generated by Django 5.0.3 on 2024-03-20 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0002_alter_secretaria_options_alter_setor_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='apelido',
            field=models.CharField(default='', max_length=62, verbose_name='Apelido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretaria',
            name='user_inclusao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão'),
        ),
        migrations.AddField(
            model_name='setor',
            name='apelido',
            field=models.CharField(default='', max_length=32, verbose_name='Apelido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='bairro',
            field=models.CharField(default='', max_length=64, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='cep',
            field=models.CharField(default='', max_length=10, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='endereco',
            field=models.CharField(default='', max_length=128, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='user_inclusao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='nome',
            field=models.CharField(max_length=164, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('dt_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('matricula', models.CharField(max_length=14, verbose_name='Matrícula')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=64, verbose_name='E-mail')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
                ('ativo', models.BooleanField(default=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.setor', verbose_name='Setor')),
                ('user_inclusao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
    ]
