# Generated by Django 5.0.3 on 2024-03-20 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0003_secretaria_apelido_secretaria_user_inclusao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instituicoes.secretaria', verbose_name='Secretaria'),
        ),
    ]
