# Generated by Django 5.0.3 on 2024-03-20 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0004_alter_setor_secretaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='user_inclusao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidor_user_inclusao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão'),
        ),
    ]
