# Generated by Django 4.2.11 on 2024-03-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0005_servidor_user_alter_servidor_user_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
