# Generated by Django 4.2.11 on 2024-03-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0006_alter_servidor_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='matricula',
            field=models.CharField(max_length=14, unique=True, verbose_name='Matrícula'),
        ),
    ]
