# Generated by Django 4.2.11 on 2024-04-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0007_alter_servidor_cpf_alter_servidor_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
