# Generated by Django 4.2.11 on 2024-04-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0010_alter_meta_servidores_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta_servidores',
            name='cpf',
            field=models.CharField(default='', max_length=14, verbose_name='Parte do CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta_servidores',
            name='secretaria',
            field=models.CharField(default='', max_length=164, verbose_name='Secretaria'),
            preserve_default=False,
        ),
    ]
