# Generated by Django 4.2.11 on 2024-04-04 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instituicoes', '0011_meta_servidores_cpf_meta_servidores_secretaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='user_inclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidor_user_inclusao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de inclusão'),
        ),
    ]
