# Generated by Django 4.2.11 on 2024-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0013_alter_servidor_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='telefone',
            field=models.CharField(max_length=16, verbose_name='Telefone'),
        ),
    ]
