# Generated by Django 4.2.16 on 2024-11-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0015_alter_servidor_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='matricula',
            field=models.CharField(max_length=50, unique=True, verbose_name='Matrícula'),
        ),
    ]
