# Generated by Django 4.2.16 on 2025-06-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0016_alter_servidor_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_Mapeamento_Secretarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_portal', models.CharField(max_length=164, verbose_name='Nome')),
                ('nome_intranet', models.CharField(max_length=164, verbose_name='Nome Intranet')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituicoes.secretaria', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Dicionário de secretarias Portal x Intranet',
                'verbose_name_plural': 'Dicionário de secretarias Portal x Intranet',
            },
        ),
    ]
