# Generated by Django 4.2.16 on 2025-06-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0017_dict_mapeamento_secretarias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict_mapeamento_secretarias',
            name='nome_intranet',
        ),
    ]
