# Generated by Django 5.1.8 on 2025-04-03 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanejamentoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField(max_length=500)),
                ('local', models.CharField(max_length=100)),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('p', 'Pendente'), ('e', 'Em andamento'), ('c', 'Concluído'), ('x', 'Cancelado')], default='p', max_length=20)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestao_acao.responsavel')),
            ],
            options={
                'verbose_name': 'Planejamento',
                'ordering': ['-id'],
            },
        ),
    ]
