# Generated by Django 4.2.16 on 2025-04-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicoes', '0016_alter_servidor_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField(max_length=500)),
                ('local', models.CharField(max_length=100)),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('p', 'Pendente'), ('e', 'Em andamento'), ('c', 'Concluído'), ('x', 'Cancelado')], default='p', max_length=20)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instituicoes.servidor')),
            ],
            options={
                'verbose_name': 'Planejamento',
                'ordering': ['data', 'horario'],
            },
        ),
    ]
