# Generated by Django 4.2.11 on 2024-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=16, null=True, verbose_name='Telefone'),
        ),
    ]
