# Generated by Django 4.2.11 on 2024-11-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicoes', '0015_alter_servidor_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(max_length=150)),
                ('msg', models.CharField(max_length=100)),
                ('lida', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadastrado_por', to='instituicoes.servidor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.servidor')),
            ],
        ),
    ]
