# Generated by Django 4.2.11 on 2024-11-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
